name: Build firmware
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:


jobs:
  build-firmware:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - keyboard: zsa/moonlander/reva
            keymap: klayi
          - keyboard: zsa/moonlander/revb
            keymap: klayi

    steps:
    - name: Checkout QMK Firmware
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        persist-credentials: false
        submodules: true

    - name: Setup QMK
      uses: ./.github/actions/setup-qmk

    - name: Build
      run: |
        qmk compile -kb ${{ matrix.keyboard }} -km ${{ matrix.keymap }} -e SKIP_GIT=1

    - name: Upload firmware
      if: matrix.keymap == 'klayi'
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ matrix.keyboard == 'zsa/moonlander/reva' && 'reva' || 'revb' }}
        path: |
          .build/zsa_moonlander_*_klayi.bin
          .build/zsa_moonlander_*_klayi.hex
        if-no-files-found: error
